name: health
description: At_Health Application for Appathon 2020
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  at_demo_data:
    git:
      url: git@github.com:atsign-company/at_demos.git
      path: at_demo_data
      ref: dev_env
  at_client_mobile:
    git:
      url: git@github.com:atsign-company/atsign_foundation.git
      path: at_client_mobile
      ref: dev_env
  gradient_app_bar: ^0.0.1
  cupertino_icons: ^0.1.3
  modal_progress_hud: any
  carousel_slider: ^2.3.1
  flutter_rounded_progress_bar: ^0.1.2
  
#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: RopaSans
      fonts:
        - asset: assets/RopaSans-Regular.ttf
  assets:
    - assets/health_logo.png
    - assets/user.png